java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    s2s:
      secrets:
        - name: microservicekey-et-sya-api
          alias: ET_SYA_S2S_SECRET
    et:
      secrets:
        - AppInsightsInstrumentationKey
