java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/et/sya-api:latest'
  ingressHost: et-sya-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: et
  keyVaults:
    et-sya-api:
      secrets:
        - name: et-sya-api-s2s-secret
          alias: ET_SYA_S2S_SECRET
        - name: Ocp-Apim-Subscription-Key
          alias: ACAS_KEY
        - name: et-api-caseworker-user-name
          alias: CASEWORKER_USER_NAME
        - name: et-api-caseworker-password
          alias: CASEWORKER_PASSWORD
    et:
      secrets:
        - AppInsightsInstrumentationKey
        - name: tornado-access-key
          alias: TORNADO_ACCESS_KEY
        - name: gov-notify-api-key
          alias: GOV_UK_NOTIFY_API_KEY
  environment:
    IDAM_API_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_JWKS_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/jwks"
    CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    ACAS_URL: "https://api-dev-acas-01.azure-api.net/ECCLDev"
    MICRO_SERVICE: "et_sya_api"
    TORNADO_URL: "https://docmosis.{{ .Values.global.environment }}.platform.hmcts.net/rs/render"
    CASE_DOCUMENT_AM_URL: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CITIZEN_PORTAL_LINK: "https://et-sya.{{ .Values.global.environment }}.platform.hmcts.net/citizen-hub/"
    SUBMIT_CASE_EMAIL_TEMPLATE_ID: "4f4b378e-238a-46ed-ae1c-26b8038192f0"
