java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  envirnment:
    SYA_API_TEST_URL: http://${SERVICE_FQDN}
  keyVaults:
    et-sya-api:
      secrets:
        - name: et-sya-api-s2s-secret
          alias: ET_SYA_S2S_SECRET
    et:
      secrets:
        - AppInsightsInstrumentationKey
        - gov-notify-api-key
