java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    SYA_API_TEST_URL: http://${SERVICE_FQDN}
  keyVaults:
    et-sya-api:
      secrets:
        - name: et-sya-api-s2s-secret
          alias: ET_SYA_S2S_SECRET
        - name: et-api-caseworker-user-name
          alias: CASEWORKER_USER_NAME
        - name: et-api-caseworker-password
          alias: CASEWORKER_PASSWORD
        - name: acas-idam-client-secret
          alias: IDAM_CLIENT_SECRET
        - name: et1-service-owner-notification-email
          alias: ET1_SERVICE_OWNER_NOTIFICATION_EMAIL
        - name: et1-ecm-dts-core-team-slack-notification-email
          alias: ET1_ECM_DTS_CORE_TEAM_SLACK_NOTIFICATION_EMAIL
    et:
      secrets:
        - AppInsightsInstrumentationKey
        - name: gov-notify-api-key
          alias: GOV_NOTIFY_API_KEY
et-sya:
  nodejs:
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/et/sya:latest # or pr
    releaseNameOverride: ${SERVICE_NAME}-et-sya
    ingressHost: et-sya-${SERVICE_FQDN}
    keyVaults:
      et:
        resourceGroup: et
        secrets:
          - AppInsightsInstrumentationKey
          - idam-secret
          - redis-access-key
          - os-places-token
          - pcq-token-key
    environment:
      IDAM_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/login
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net/o/token
      REDIS_HOST: et-sya-session-storage-aat.redis.cache.windows.net
      ET_SYA_API_HOST: http://{{ .Release.Name }}-et-sya-api
      PCQ_ENABLED: true

idam-pr:
  redirect_uris:
    ET Citizen Submit Your Appeal:
      - https://et-sya-${SERVICE_FQDN}/oauth2/callback
