java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/et/sya-api:latest'
  ingressHost: et-sya-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: et
  keyVaults:
    et-sya-api:
      secrets:
        - name: et-sya-api-s2s-secret
          alias: ET_SYA_S2S_SECRET
    et:
      secrets:
        - AppInsightsInstrumentationKey

  environment:
    IDAM_API_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_JWKS_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/jwks"
    CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    MICRO_SERVICE: "et_sya_api"
