java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    et-cos:
      secrets:
        - name: et-cos-s2s-secret
          alias: ET_COS_S2S_SECRET
    et:
      secrets:
        - AppInsightsInstrumentationKey
