java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    et:
      secrets:
        - AppInsightsInstrumentationKey
        - name: s2s-case-api-secret
          alias: ET_COS_S2S_SECRET
