server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.et.syaapi.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/et-sya-api/,optional:configtree:/mnt/secrets/et/"
  application:
    name: ET SYA API
  main:
    allow-bean-definition-overriding: true

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  api:
    url: ${IDAM_API_BASEURL:http://localhost:5000}
    jwksUrl: ${IDAM_JWKS_BASEURL:http://localhost:5000/o/jwks}
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://localhost:4502}
    secret: ${ET_SYA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${MICRO_SERVICE:et_sya_api}

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://localhost:4452}
  search:
    page_size: ${CCD_SEARCH_PAGE_SIZE:100}

case_document_am:
  url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}
  max_retries: 3

acas:
  api:
    url: "https://api-dev-acas-01.azure-api.net/ECCLDev"
    key: "380e7fad52b2403abf42575ca8fba6e2" # This environment variable can be set in your local environment. Do not change this value.

tornado:
  api:
    url: ${TORNADO_URL:http://localhost:8090/rs/render}
    key: ${TORNADO_ACCESS_KEY:ignored_default_value}

notifications:
  govNotifyApiKey: ${GOV_UK_NOTIFY_API_KEY:et1live-21beac2b-d979-4771-bbb5-e34b62cba543-6ce0eb4b-98ee-45a1-8b0c-5345f3754423}
  sampleEmailTemplateId: "4ea3cf16-0cbb-4f27-8cfb-a084b126086e"
  sampleSubmitCaseEmailTemplateId: "af0b26b7-17b6-4643-bbdc-e296d11e7b0c"
  submitCaseEmailTemplateId: ${SUBMIT_CASE_EMAIL_TEMPLATE_ID:4f4b378e-238a-46ed-ae1c-26b8038192f0}

pdf:
  source: "classpath:ET1_0922.pdf"
