server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.et.syaapi.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/et-sya-api/,optional:configtree:/mnt/secrets/et/"
  application:
    name: ET SYA API
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  api:
    url: ${IDAM_API_BASEURL:http://localhost:5000}
    jwksUrl: ${IDAM_JWKS_BASEURL:http://localhost:5000/o/jwks}
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://localhost:4502}
    secret: ${ET_SYA_S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: ${MICRO_SERVICE:et_sya_api}
  client:
    id: et-sya-api
    secret: ${IDAM_CLIENT_SECRET:AAAAAAAAAAAAAAAA}
    scope: openid profile roles

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://localhost:4452}
  search:
    page_size: ${CCD_SEARCH_PAGE_SIZE:100}

case_document_am:
  url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}
  max_retries: 3

acas:
  api:
    url: ${ACAS_BASE_URL:https://api-dev-acas-01.azure-api.net/ECCLDev}
    key: ${ACAS_KEY:AAAAAAAAAAAAAAAAAAAA}
    # This environment variable can be set in your local environment. Do not change this value.

tornado:
  api:
    url: ${TORNADO_URL:http://localhost:8090/rs/render}
    key: ${TORNADO_ACCESS_KEY:ignored_default_value}

notifications:
  citizenPortalLink: ${CITIZEN_PORTAL_LINK:https://localhost:3001/citizen-hub/}
  govNotifyApiKey: ${GOV_UK_NOTIFY_API_KEY:AAAAAAAAAAAAAAAAA}
  submitCaseEmailTemplateId: ${SUBMIT_CASE_EMAIL_TEMPLATE_ID:a4045b26-3914-4c13-a06e-6fb64a99ee2f}
  cySubmitCaseEmailTemplateId: ${CY_SUBMIT_CASE_EMAIL_TEMPLATE_ID:17ff79da-3bbf-4c82-ab44-48038c792d23}
  submitCaseDocUploadErrorEmailTemplateId: ${SUBMIT_CASE_DOC_UPLOAD_ERROR_EMAIL_TEMPLATE_ID:abba853d-efac-41fe-a985-bdd50c95410c} // todo figure out which template we need.
  et1ServiceOwnerNotificationEmail: ${ET1_SERVICE_OWNER_NOTIFICATION_EMAIL:ignored_default_value}
  et1EcmDtsCoreTeamSlackNotificationEmail: ${ET1_ECM_DTS_CORE_TEAM_SLACK_NOTIFICATION_EMAIL:ignored_default_value}
pdf:
  english: "ET1_2222.pdf"
  welsh: "CY_ET1_2222.pdf"

caseWorkerUserName: ${CASEWORKER_USER_NAME:user_name}
caseWorkerPassword: ${CASEWORKER_PASSWORD:password}
