idam:
  api:
    url: http://localhost:5000
    jwksUrl: http://localhost:5000/o/jwks
  s2s-auth:
    url: http://localhost:8489
    secret: AAAAAAAAAAAAAAAA

core_case_data:
  api:
    url: http://localhost:4452

case_document_am:
  url: http://localhost:5005
