server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.et.syaapi.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/et-sya-api/,optional:configtree:/mnt/secrets/et/"
  application:
    name: ET SYA API
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

azure:
  application-insights:
    instrumentation-key: ${APP_INSIGHTS_KEY:00000000-0000-0000-0000-000000000000}

idam:
  api:
    url: ${IDAM_API_BASEURL:http://localhost:5000}
    jwksUrl: ${IDAM_JWKS_BASEURL:http://localhost:5000/o/jwks}
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://localhost:4502}
    secret: ${ET_SYA_S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: ${MICRO_SERVICE:et_sya_api}
  client:
    id: et-sya-api
    secret: ${IDAM_CLIENT_SECRET:AAAAAAAAAAAAAAAA}
    scope: openid profile roles

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://localhost:4452}
  search:
    page_size: ${CCD_SEARCH_PAGE_SIZE:100}

case_document_am:
  url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}
  max_retries: 3

acas:
  api:
    url: ${ACAS_BASE_URL:https://api-dev-acas-01.azure-api.net/ECCLDev}
    key: ${ACAS_KEY:AAAAAAAAAAAAAAAAAAAA}
    # This environment variable can be set in your local environment. Do not change this value.

tornado:
  api:
    url: ${TORNADO_URL:http://localhost:8090/rs/render}
    key: ${TORNADO_ACCESS_KEY:ignored_default_value}

notifications:
  citizenPortalLink: ${CITIZEN_PORTAL_LINK:https://localhost:3001/citizen-hub/}
  exuiCaseDetailsLink: ${EXUI_CASE_DETAILS_URL:http://localhost:3455/cases/case-details/}
  govNotifyApiKey: ${GOV_UK_NOTIFY_API_KEY:AAAAA}
  sampleEmailTemplateId: "4ea3cf16-0cbb-4f27-8cfb-a084b126086e"
  sampleSubmitCaseEmailTemplateId: "af0b26b7-17b6-4643-bbdc-e296d11e7b0c"
  submitCaseEmailTemplateId: ${SUBMIT_CASE_EMAIL_TEMPLATE_ID:4f4b378e-238a-46ed-ae1c-26b8038192f0}
  cySubmitCaseEmailTemplateId: ${CY_SUBMIT_CASE_EMAIL_TEMPLATE_ID:f61f7f2a-4825-491b-bc48-0299f1a8ba23}
  applicationAcknowledgementTypeC: ${APPLICATION_ACKNOWLEDGEMENT_TYPE_C:197c69b6-254c-4f8d-8909-e85549496d8b}
  applicationAcknowledgementYes: ${APPLICATION_ACKNOWLEDGEMENT_YES:d5f319f1-229f-4dcb-9293-f164bb327601}
  applicationAcknowledgementNo: ${APPLICATION_ACKNOWLEDGEMENT_NO:e6c8b8c4-e58b-4bae-a8ec-cca68bca0c4e}
  respondentCopyTypeA: ${RESPONDENT_COPY_A:a2ffb9b3-8bf7-4e9a-aab8-08a6c5a82636}
  respondentCopyTypeB: ${RESPONDENT_COPY_B:59ccc472-8f2e-43e4-b275-832f1c714eff}
  tribunalAcknowledgement: ${TRIBUNAL_ACKNOWLEDGEMENT:d82aa18a-1a3d-44af-91fa-565d178f5e0e}
  tribunalResponse: ${TRIBUNAL_RESPONSE:9da290ff-c7da-4897-80d2-114361271dfa}
  claimantResponseYes: ${CLAIMANT_RESPONSE_YES:091abb61-0a21-4208-b3b6-22121e8682be}
  claimantResponseNo: ${CLAIMANT_RESPONSE_NO:0727a137-322f-458b-9941-ee8b6d3c11c2}
  respondentResponse: ${RESPONDENT_RESPONSE:63b0488f-134c-4bf2-8dea-40df4d158628}

pdf:
  english: "ET1_2222.pdf"
  welsh: "CY_ET1_2222.pdf"
  contact_tribunal_template: "EM-TRB-EGW-ENG-00068.docx"
  claimant_response_template: "EM-TRB-EGW-ENG-00069.docx"

caseWorkerUserName: ${CASEWORKER_USER_NAME:user_name}
caseWorkerPassword: ${CASEWORKER_PASSWORD:password}
