server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.et.syaapi.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/et-sya-api/,optional:configtree:/mnt/secrets/et/"
  application:
    name: ET SYA API
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  api:
    url: ${IDAM_API_BASEURL:http://localhost:5000}
    jwksUrl: ${IDAM_JWKS_BASEURL:http://localhost:5000/o/jwks}
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://localhost:4502}
    secret: ${ET_SYA_S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: ${MICRO_SERVICE:et_sya_api}
  client:
    id: et-sya-api
    secret: ${IDAM_CLIENT_SECRET:AAAAAAAAAAAAAAAA}
    scope: openid profile roles

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://localhost:4452}
  search:
    page_size: ${CCD_SEARCH_PAGE_SIZE:100}

case_document_am:
  url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}
  max_retries: 3

acas:
  api:
    url: ${ACAS_BASE_URL:https://api-dev-acas-01.azure-api.net/ECCLDev}
    key: ${ACAS_KEY:AAAAAAAAAAAAAAAAAAAA}
    # This environment variable can be set in your local environment. Do not change this value.

tornado:
  api:
    url: ${TORNADO_URL:http://localhost:8090/rs/render}
    key: ${TORNADO_ACCESS_KEY:ignored_default_value}

notifications:
  citizenPortalLink: ${CITIZEN_PORTAL_LINK:https://localhost:3001/citizen-hub/}
  govNotifyApiKey: ${GOV_UK_NOTIFY_API_KEY:mtd_test-002d2170-e381-4545-8251-5e87dab724e7-ac8ef473-1f28-4bfc-8906-9babd92dc5d8}
  sampleEmailTemplateId: "4ea3cf16-0cbb-4f27-8cfb-a084b126086e"
  sampleSubmitCaseEmailTemplateId: "af0b26b7-17b6-4643-bbdc-e296d11e7b0c"
  submitCaseEmailTemplateId: ${SUBMIT_CASE_EMAIL_TEMPLATE_ID:0bd2e5b4-c26d-4f65-a859-00f66704605a}
  cySubmitCaseEmailTemplateId: ${CY_SUBMIT_CASE_EMAIL_TEMPLATE_ID:f61f7f2a-4825-491b-bc48-0299f1a8ba23}
  submitCaseDocUploadErrorEmailTemplateId: ${SUBMIT_CASE_DOC_UPLOAD_ERROR_EMAIL_TEMPLATE_ID:3007a1e9-13b0-4bf9-9753-398ea91b8564}
  et1ServiceOwnerNotificationEmail: ${ET1_SERVICE_OWNER_NOTIFICATION_EMAIL:test@justice.gov.uk}
  et1EcmDtsCoreTeamSlackNotificationEmail: ${ET1_ECM_DTS_CORE_TEAM_SLACK_NOTIFICATION_EMAIL:test@moj.org.slack.com}
pdf:
  english: "ET1_2222.pdf"
  welsh: "CY_ET1_2222.pdf"
