apiVersion: v2
appVersion: "1.0"
description: A Helm chart for et-syaapi App
name: et-et-syaapi
home: https://github.com/hmcts/et-syaapi
version: 0.0.1
maintainers:
  - name: HMCTS et team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
